### ISSUE TITLE
Strange Brigade - corruption in faces vs. LLVM

### ISSUE THREAD

**Issue by aufkrawall** [daniel-schuermann/mesa#169]
native Vulkan game

LLVM:
![Screenshot_20191229_123716](https://user-images.githubusercontent.com/13510490/71556379-3e4d2600-2a38-11ea-86b1-f42decbf4669.png)

ACO (grainy and blocky artifacts in her face):
![Screenshot_20191229_123730](https://user-images.githubusercontent.com/13510490/71556372-31c8cd80-2a38-11ea-9708-0f9c39bf53c3.png)

RenderDoc capture:
https://drive.google.com/open?id=1CwnQQPyxpmU_smF0ijZNqTwp9TxK06s2

RX 570 8GB
mesa-git  20.0.0_devel.118799.ff3a2576a45 (not ACO fork)

**Comment by aufkrawall** [comment]
Could confirm the same corruption on Navi.

**Comment by aufkrawall** [comment]
Fixed with this branch 7b444ba5ef1818f81c1892c5babd02ed18186b02 . :)
Going to post some numbers in the benchmark ticket that you should like.

**Comment by pendingchaos** [comment]
More precisely, the commit should be https://github.com/daniel-schuermann/mesa/commit/5d7675a739736450b947b8d51db80ed14567e7c4 (though I might do a different fix in the end)

There are still some subtle differences from LLVM, since that commit doesn't completely fix the issue. I doubt the issue affects performance at all

That commit isn't upstreamed btw

**Comment by aufkrawall** [comment]
Not reproducible anymore with mesa 20.1.4 & RX 480.
